---
title: Ted Slocum
timezone: UTC
collections:
  authors:
    title: Authors
    output: true
  blog_names:
    title: Blog Names
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: authors
  values:
    layout: author
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
  values:
    layout: default
email: sted9000@gmail.com
description: Ted Slocum's personal website and blog, where he thinks online.
baseurl: "/"
url: https://sted9000.github.io
github_username: sted9000
sass:
  sass_dir: _sass
  style: compressed
future: false
permalink: "/:categories/:year/:month/:day/:title"
markdown: kramdown
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-sitemap
